runtime: nodejs10

instance_class: F4_1G
automatic_scaling:
  min_instances: 1
  max_instances: 1
  # max_concurrent_requests: 80

inbound_services:
- warmup

# instance_class: B1
# manual_scaling:
#   instances: 1
